docs: Add swagger docs
IntelliTect/Coalesce pull request #433
Opened 2024-09-02 15:35 UTC by meghanmae

fixes #100

2024-09-03 15:34 UTC, ascott18 requested changes

2024-09-03 15:34 UTC, ascott18 commented on docs/topics/coalesce-swashbuckle-without.png
Both images are showing as invalid/corrupted files on Github

2024-09-03 15:34 UTC, ascott18 commented on docs/topics/coalesce-swashbuckle.md
> +When using Coalesce to generate API endpoints the default Swagger generation can sometimes result in verbose and confusing API definitions, especially when dealing with DataSources and Behaviors. To
```suggestion
When using Coalesce to generate API endpoints, the default Swagger generation can sometimes result in verbose and confusing API definitions, especially when dealing with DataSources and Behaviors. To address these issues, the `IntelliTect.Coalesce.Swashbuckle` package offers enhancements for Swagger definitions, making your Coalesce-generated APIs clearer and more manageable.
```

2024-09-03 15:34 UTC, ascott18 commented on docs/topics/coalesce-swashbuckle.md
> +- Standard Parameters: It removes unnecessary parameters related to behaviors and data sources, improving the clarity of the generated swagger API documentation.
I think just a simple high level summary of the effects is OK. We don't need to detail the exact functionality of each individual Filter implementation class - we can consider those as internal implementation details. The user will get a good enough idea of the effects.

```suggestion
The primary effect is an adjustment of parameter definitions to account for Coalesce's custom model binders that create instances of Data Sources and Behaviors on each request. These parameters will be updated in the OpenAPI document to account for data source parameters, filter parameters, and other model-specific customizations.
```

2024-09-03 15:34 UTC, ascott18 commented on docs/topics/coalesce-swashbuckle.md
> +# Coalesce Swashbuckle
```suggestion
# OpenAPI/Swagger
```

2024-09-03 15:34 UTC, ascott18 commented on docs/topics/coalesce-swashbuckle.md
> +
Lets update all references to "Swagger" to "OpenAPI" where appropriate, or to "Swashbuckle" when referring to the specific nuget packages.

Swagger is a suite of tools and services created and sold by SmartBear around the OpenAPI standard. We should include maybe a short blurb in the first paragraph for searching purposes, but nothing else aside from the references in Swashbuckle's method names (which are named so for legacy/compatibility reasons). 

Something like "... OpenAPI (sometimes referred to as its pre-2015 name "Swagger") ..."

2024-09-03 15:34 UTC, ascott18 commented on docs/topics/coalesce-swashbuckle.md
> +    public DateTime NextAppoitment { get; set; }
```suggestion
    public DateTime NextAppointment { get; set; }
```

2024-09-03 15:34 UTC, ascott18 commented on docs/topics/coalesce-swashbuckle.md
> +    // Additional parameters
```suggestion
    // Additional properties
```

2024-09-08 22:07 UTC, meghanmae commented on docs/topics/coalesce-swashbuckle-without.png
Made them into jpgs rather than pngs, they seem to be happier!

2024-09-16 23:23 UTC, merged